/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blues_ffmpegdemo_NativePlayer */

#ifndef _Included_com_blues_ffmpegdemo_NativePlayer
#define _Included_com_blues_ffmpegdemo_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blues_ffmpegdemo_NativePlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_blues_ffmpegdemo_NativePlayer_playVideo
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
